services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.0
    container_name: aau_connect_keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://hopper.proxy.rlwy.net:29442/railway
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: bxIzDyHpYRNqKMtcTfHpQrHeYqLiUxOn
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak/aau-connect-realm.json:/opt/keycloak/data/import/realm.json:ro
    command: start-dev --import-realm
    networks:
      - aau-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: aau_connect_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - aau-network

volumes:
  postgres_data:
  rabbitmq_data:


networks:
  aau-network:
    driver: bridge
